### ISSUE TITLE
allow for panning when using orbit controls / add free camera

### ISSUE THREAD

**Issue by cwill** [rpearl/chlorophyll#13]
Not all arrangements of pixels are going to easily fit in one viewport (e.g. long/tall wibbly shapes), and using controls that orbit around the center of a model when the working group is off to the side is disorienting.

A free camera mode or the ability to pan the camera more easily would make this easier.

**Comment by rpearl** [comment]
Panning exists with rightclick+drag, but I am not sure how it interacts with the center target

**Comment by cwill** [comment]
Fine for now. May want to make camera improvements in the future but existing camera covers this bug.
