### ISSUE TITLE
Lots of mapping UI assumes a 2D projection mapping

### ISSUE THREAD

**Issue by rpearl** [rpearl/chlorophyll#47]
For linear mappings (needed to generate groups from strips, even before any UI exists for linear mappings), we need to be able to have current mappings that do other things to the `mappingConfigInspector`.

**Comment by cwill** [comment]
yeah, been wanting to move this around a bit. In general, we've got these manager objects, and the individual objects they manage, and we should probably figure out a good standardized division of what UI stuff goes where.

**Comment by rpearl** [comment]
Fixed in eda2f83
