### ISSUE TITLE
changing mapping type of a new mapping blocks undo keybinding

### ISSUE THREAD

**Issue by cwill** [rpearl/chlorophyll#53]
Minor but bizarre issue. Repro steps:
1. create a new group
2. create a new mapping
3. change its mapping type
4. attempt to undo via mod+z (doesn't work, worldState.undo() is never called)
Notably, undo still works via the dropdown menu, and starts working again if the mapping is deselected and reselected, or if you configure and then close it.

Vague suspicion that d3 might be doing something odd with keybindings, and the problem crops up when we create a new widget.

**Comment by rpearl** [comment]
This appears to have to do with the "Mapping type" dropdown being selected. If you defocus it, undo begins working. 

https://craig.is/killing/mice Mousetrap's default `stopCallback` returns true in that case; we should figure out the actual criteria we want to use to skip callbacks.
