### ISSUE TITLE
group visibility checkbox rendered incorrectly

### ISSUE THREAD

**Issue by cwill** [rpearl/chlorophyll#54]
![bug](http://i.imgur.com/eTvi8oS.png)

**Comment by rpearl** [comment]
Hmm, can't repro here. Some weird css problem then :/

**Comment by cwill** [comment]
I'm using old-ass firefox so I'm going to assume this is a property of browser rather than in our code.

**Comment by cwill** [comment]
Happens in newer firefox too, reopened.
