### ISSUE TITLE
Add "changed" events to groups and mappings

### ISSUE THREAD

**Issue by cwill** [rpearl/chlorophyll#66]
We already have some places in the pattern code where it would be nice to be able to respond to a group or mapping changing. For example, if we could add some points to a group or fiddle with a mapping's settings while running a pattern, this would make adjusting patterns and mappings in concert with each other much easier.

I'm anticipating that these sorts of cases are only going to increase, so we should probably start using events to deal with this rather than the occasional hacky callback or checking a value in some other manager object.

**Comment by rpearl** [comment]
patches.js already adds the addEventListener interface to graphs. We can pretty easily extend that to work with more objects types. (And probably move it out of patches.js)
